### ISSUE TITLE
Could throw a more helpful error on IllegalFormatConversionException

### ISSUE THREAD

**Issue by WhittlesJr** [gfredericks/like-format-but-with-named-args#1]
I currently wrap named-format like so:

```
(defn named-format
  [format-str arg-map & [other-info]]
  (try
    (named-format/named-format format-str arg-map)
    (catch java.util.IllegalFormatConversionException e
      (throw (ex-info "Unable to use named-format!" {:format-str format-str
                                                     :arg-map    arg-map
                                                     :other-info other-info})))))

```

The "other info" is helpful for me figuring out exactly which part of my data is causing the problem, but probably wouldn't be useful for everyone. It is helpful to have :format-str and :arg-map always though.

I don't know, any thoughts?

**Comment by gfredericks** [comment]
Hi and thanks for the suggestion!

I like the idea of exposing the arguments in exceptions.

Several notes:

- I **don't** like `other-info` -- that's a very generic feature and there's no reason to add it here and not expect every library function everywhere to do the same thing
- The `ex-info` should have the exception attached as the cause (third arg)
- This can't be implemented purely as a wrapper, as that would thwart the compile-time-parsing feature; the try/catch should probably be inlined around each call to `clojure.core/format`

**Comment by WhittlesJr** [comment]
Sounds good to me! Would you like me to put together a PR, or would you like to implement this yourself?

**Comment by gfredericks** [comment]
PR please -- thanks!
